#!/usr/bin/env python3
"""Writes Sources/QuothCore/UI/AcknowledgementsText.swift from the licence
files of Quoth and its dependencies, for the Acknowledgements window.

    swift package resolve && python3 scripts/make-acknowledgements.py

Run it again whenever a dependency changes. The App Store build ships only
WhisperKit, so Sparkle and swift-argument-parser are listed for the direct
build only.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHECKOUTS = ROOT / ".build" / "checkouts"

def read(path):
    return path.read_text(encoding="utf-8").strip()

shared = [
    ("Quoth", "Quoth is based on Parrot by Humanitas Labs.\n\n" + read(ROOT / "LICENSE")),
    ("WhisperKit (Argmax OSS)", read(CHECKOUTS / "argmax-oss-swift" / "LICENSE")
        + "\n\n" + read(CHECKOUTS / "argmax-oss-swift" / "NOTICES")),
    ("Whisper models", "Whisper by OpenAI, released under the MIT License. "
        "Core ML conversions by Argmax, Inc. (argmaxinc/whisperkit-coreml), MIT License."),
]
direct = [
    ("Sparkle", read(CHECKOUTS / "Sparkle" / "LICENSE")),
    ("Swift Argument Parser", read(CHECKOUTS / "swift-argument-parser" / "LICENSE.txt")),
]

def section(title, text):
    rule = "=" * 72
    return f"{rule}\n{title}\n{rule}\n\n{text}\n"

def literal(sections):
    body = "\n".join(section(t, x) for t, x in sections)
    # A raw multi-line literal: no escapes are interpreted.
    return '#"""\n' + body + '\n"""#'

swift = f"""// Generated by scripts/make-acknowledgements.py. Do not edit by hand.

/// The licence texts shown in the Acknowledgements window.
enum AcknowledgementsText {{
    static let shared = {literal(shared)}

    #if APPSTORE
    static let all = shared
    #else
    static let all = shared + "\\n" + {literal(direct)}
    #endif
}}
"""
out = ROOT / "Sources" / "QuothCore" / "UI" / "AcknowledgementsText.swift"
out.write_text(swift, encoding="utf-8")
print(f"wrote {out.relative_to(ROOT)}")
