import AppKit

/// The licence texts of Quoth and what it is built on, from the menu's
/// Acknowledgements…. One window, reused; the text is generated by
/// scripts/make-acknowledgements.py.
@MainActor
enum AcknowledgementsWindow {
    private static var window: NSWindow?

    static func show() {
        let window = self.window ?? make()
        self.window = window
        NSApp.activate(ignoringOtherApps: true)
        window.makeKeyAndOrderFront(nil)
    }

    private static func make() -> NSWindow {
        let window = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 620, height: 560),
            styleMask: [.titled, .closable, .resizable],
            backing: .buffered,
            defer: false
        )
        window.title = "Acknowledgements"
        window.isReleasedWhenClosed = false
        window.center()

        let scroll = NSTextView.scrollableTextView()
        let text = scroll.documentView as! NSTextView
        text.isEditable = false
        text.isSelectable = true
        text.textContainerInset = NSSize(width: 16, height: 16)
        text.font = .monospacedSystemFont(ofSize: 11, weight: .regular)
        text.textColor = .labelColor
        text.string = AcknowledgementsText.all
        window.contentView = scroll
        return window
    }
}
